### ISSUE TITLE
multipassd fails to start without network connectivity

### ISSUE THREAD

**Issue by cmars** [CanonicalLtd/multipass#404]
On an Ubuntu 18.04 host, I was unable to use multipass in airplane mode:

```
$ multipass list
list failed: Connect Failed
```

Looks like multipassd is failing to start because it can't contact cloud-images; syslog contained: 
```
Sep 22 14:40:39 slate multipassd[17469]: Host cloud-images.ubuntu.com not found
Sep 22 14:40:39 slate systemd[1]: snap.multipass.multipassd.service: Main process exited, code=exited, status=1/FAILURE
Sep 22 14:40:39 slate systemd[1]: snap.multipass.multipassd.service: Failed with result 'exit-code'.
Sep 22 14:40:39 slate systemd[1]: snap.multipass.multipassd.service: Service hold-off time over, scheduling restart.
Sep 22 14:40:39 slate systemd[1]: snap.multipass.multipassd.service: Scheduled restart job, restart counter is at 4.
Sep 22 14:40:39 slate systemd[1]: Stopped Service for snap application multipass.multipassd.
```

multipassd should tolerate and recover from network partitions, and still allow access to VMs while offline.

**Comment by Saviq** [comment]
Hi @cmars is this with the `stable` version? Could you please try `edge`? It should be fixed there.

**Comment by townsend2010** [comment]
I think this is still a problem and yes, we should allow access to instances even if the network can't be reached.  Going a bit further, we should still allow launching of instances if the image is cached and perhaps display a warning to the user in such cases.

**Comment by cmars** [comment]
Refreshed to the edge snap and I'm able to access instances while offline. Thanks!

**Comment by townsend2010** [comment]
Oh, lol, I guess it is fixed:)  I remember the fix now...it just took a moment to knock that rust off of my brain:)  I'll go ahead and close this.

**Comment by ricab** [comment]
For the record, the duplicated issue: #316
